/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Configs: () => import('#controllers/configs_controller'),
  Inscriptions: () => import('#controllers/inscriptions_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Teams: () => import('#controllers/teams_controller'),
}
